default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  secret_key: '{{ cookiecutter.secret_key }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'
  pg_server: '{{ cookiecutter.pg_server }}'
  pg_user: '{{ cookiecutter.pg_user }}'
  pg_password: '{{ cookiecutter.pg_password }}'
  pg_db: '{{ cookiecutter.pg_db }}'
  superuser_email: '{{cookiecutter.superuser_email}}'
  superuser_password: '{{cookiecutter.superuser_password}}'
