default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  domain_main: '{{ cookiecutter.domain_main }}'
  domain_staging: '{{ cookiecutter.domain_staging }}'
  docker_swarm_stack_name_main: '{{ cookiecutter.docker_swarm_stack_name_main }}'
  docker_swarm_stack_name_staging: '{{ cookiecutter.docker_swarm_stack_name_staging }}'
  secret_key: '{{ cookiecutter.secret_key }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'
  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  docker_image_backend: '{{ cookiecutter.docker_image_backend }}'
