version: '3.3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: backend
  celeryworker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: celery-worker
  frontend:
    build: 
      context: ./frontend
      args:
          FRONTEND_ENV: ${FRONTEND_ENV-production}
