version: '3.8'

services:
  db:
    image: postgres:13.0
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - "8080:80"
    build:
      context: ./app
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: /start-reload.sh
    volumes:
      - ./app:/app

volumes:
  db-volume:
