version: '3.3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: backend
      args: 
        env: dev
  celeryworker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: celery-worker
      args: 
        env: dev
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend-tests
      args: 
        env: dev
  frontend:
    build: 
      context: ./frontend
      args: 
        FRONTEND_ENV: dev
