name: Generate Client

on:
  pull_request:
    types:
    - opened
    - synchronize
    paths-ignore:
      - 'release-notes.md'
      - development.md
      - deployment.md
      - SECURITY.md
      - README.md
      - LICENSE
      - .pre-commit-config.yaml
      - .gitignore
      - .gitattributes
      - img/*
      - hooks/*
      - .copier/*

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ github.token }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.15"
        enable-cache: true
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - run: uv sync
      working-directory: backend
    - run: uv run bash scripts/generate-client.sh
      env:
        VIRTUAL_ENV: backend/.venv
    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add frontend/src/client
        git diff --staged --quiet || git commit -m "✨ Autogenerate frontend client"
        git push
